// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace ClubSwimmers.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230713125416_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("Entities.Models.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("ClubId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Address = " 255 saint-georges Beauce , G4Y 5D9",
                            Country = "Canada",
                            Name = "CNRB"
                        },
                        new
                        {
                            Id = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            Address = " 1223 Saint-foy Quebec , 4v5 7x9",
                            Country = "Canada",
                            Name = "NSh"
                        });
                });

            modelBuilder.Entity("Entities.Models.Swimmer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("SwimmerId");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainingGroup")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Swimmers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80abbca8-664d-4b20-b5de-024705497d4a"),
                            Age = 14,
                            ClubId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Emile Bergeron",
                            TrainingGroup = "Elite"
                        },
                        new
                        {
                            Id = new Guid("86dba8c0-d178-41e7-938c-ed49778fb52a"),
                            Age = 22,
                            ClubId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            Name = "Sandra Bullock",
                            TrainingGroup = "Master I"
                        },
                        new
                        {
                            Id = new Guid("021ca3c1-0deb-4afd-ae94-2159a8479811"),
                            Age = 7,
                            ClubId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            Name = "Amina Diop",
                            TrainingGroup = "Initiation II"
                        });
                });

            modelBuilder.Entity("Entities.Models.Swimmer", b =>
                {
                    b.HasOne("Entities.Models.Club", "Club")
                        .WithMany("Swimmers")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("Entities.Models.Club", b =>
                {
                    b.Navigation("Swimmers");
                });
#pragma warning restore 612, 618
        }
    }
}
